### PR TITLE
Start tools reference section

### PR DESCRIPTION
**Pull request by lisa-parity**

### CODE REVIEW

**Comment by sacha-l** [comment]
Is this good to merge?

**Comment by lisa-parity** [comment]
This section is messed up: 
### Combine derivation paths and passwords
and I'll add more but it is probably okay to merge and iterate

**Comment by lisa-parity** [comment]
@shawntabrizi, the "Combine derivation paths and passwords" part is part I'm looking for a little help figuring out. It works as originally documented using //polkadot/0 but I can't figure out where the public key came from.
Since this is moving into the sandbox I'm going to mark it as Ready for Review, but the subkey section is the main meat here.

**Review by sacha-l — APPROVED** [review]
I say we get this in and iterate in a more targeted review phase.

**Pull request merged**
