### PR TITLE
Lg/pallet reference

### PR DESCRIPTION
**Pull request by lisa-parity**
Migrating from:
https://docs.substrate.io/v3/runtime/frame/

The idea here is to reduce the overlap and redundancy between pallet reference (with a short description and links to both the reference and to source for every pallet) and the actual Rust documentation for pallets. It was a lot of lines (from almost 500 to less than 100) for very little new information.
This pallet summary lives in the reference section.
The Frame overview/conceptual topics will move into the Runtime discussion in fundamentals.

@sacha-l @NukeManDan Is there a reason why we don't point directly to the Rust page for each pallet? I needed to do that within this structure, but maybe it's a Gatsby thing.

### CODE REVIEW

**Comment by NukeManDan** [comment]
IMHO this section is not needed in it's entirety. I would instead help users understand how to peruse the source and the rust docs on their own, vs. manually keeping this maintaining all this... not often but FRAME pallets do get reordered and more added/removed.

**Comment by lsgunnlsgunn** [comment]
I'm a bit confused. What do you mean by " it needed inits entirety" exactly? At less than 100 lines, it doesn't seem like an overloaded topic and I found myself wanting a quick summary of the pallets available. The main point here is to summarize and point to the Rust docs directly.

**Comment by cc-michael-x** [comment]
I recently completely these tutorials from substrate and found it extremely helpful to get a quick list of some of the many pallets that are available to use. It's more of an eye opener to show people what pallets are out there! I even took most of them and started integrated each one in my own blockchain as a challenge to learn on my own.

**Comment by cc-michael-x** [comment]
> I recently completely these tutorials from substrate and found it extremely helpful to get a quick list of some of the many pallets that are available to use. It's more of an eye opener to show people what pallets are out there! I even took most of them and started integrated each one in my own blockchain as a challenge to learn on my own.

I know this is already merged, but I just wanted to give my feedback on this change and how it was taken from my point of view as someone who started off with these tutorials.

**Comment by sacha-l** [comment]
Hey @cc-michael-x - thanks for the feedback, much appreciated! Its always great to get validation from people like you who are diving in from a fresh perspective 🙏🏻 🚀

**Pull request merged**
